apiVersion: v1
kind: Service
metadata:
  name: front-end-service-sample-app
spec:
  selector:
    app: sample-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
